version: '3.8'

services:
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 'fatec'
      MYSQL_DATABASE: "clientes"  
    container_name: "mysql-server"
    ports:
      - 3307:3306
    volumes:
      - ./data/mysql:/var/lib/mysql

  